# Generated by Django 5.2.17 on 2026-09-08 18:19

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0205_merge_20260615_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=250)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('basis', models.CharField(choices=[('fixed', 'fixed'), ('percent', 'percent')], default='fixed', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('apply_to', models.CharField(choices=[('unit', 'unit'), ('line', 'line')], default='unit', max_length=10)),
                ('required', models.BooleanField(default=True)),
                ('decline_label', models.CharField(blank=True, max_length=250)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wsm_fees', to='product.product')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='OptionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('label', models.CharField(blank=True, max_length=250)),
                ('prompt_type', models.CharField(choices=[('choice_one', 'choice_one'), ('choice_many', 'choice_many'), ('text', 'text'), ('date', 'date'), ('datetime', 'datetime'), ('image', 'image')], default='choice_one', max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wsm_option_sets', to='product.product')),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='OptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('sku_fragment', models.CharField(blank=True, max_length=100)),
                ('price_delta', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('sort_order', models.IntegerField(default=0)),
                ('option_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='wsm_compose.optionset')),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='DealerTierOptionPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_group', models.CharField(max_length=100)),
                ('price_delta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('option_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_deltas', to='wsm_compose.optionvalue')),
            ],
            options={
                'ordering': ('tier_group', 'pk'),
                'constraints': [models.UniqueConstraint(fields=('option_value', 'tier_group'), name='wsm_compose_one_tier_row_per_group')],
            },
        ),
    ]
