# Generated by Django 5.2.17 on 2026-09-09 21:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0205_merge_20260615_1308'),
        ('shipping', '0037_merge_20250630_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='What the shopper sees on the cart line, e.g. Freight crating.', max_length=250)),
                ('sku', models.CharField(blank=True, help_text='Your own code for this charge, carried through to the order.', max_length=100)),
                ('basis', models.CharField(choices=[('fixed', 'A flat amount of money'), ('percent', 'A percentage of the item price')], default='fixed', help_text='A flat amount of money, or a percentage of the configured product price before any other charge.', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='A flat charge, or the percentage when Charged as is a percentage (enter 8.25 for 8.25%). Never negative, and never above 100 for a percentage.', max_digits=12)),
                ('apply_to', models.CharField(choices=[('unit', 'Per item'), ('line', 'Once per line')], default='unit', help_text='Per item charges once for every item ordered. Once per line charges once no matter how many are ordered.', max_length=10)),
                ('required', models.BooleanField(default=True, help_text='Always charged. Turn this off to let the shopper decline the charge.')),
                ('decline_label', models.CharField(blank=True, help_text='Only used when the charge can be declined: the wording of the decline option, e.g. No crate, I will collect.', max_length=250)),
                ('product', models.ForeignKey(help_text='The product this charge is attached to.', on_delete=django.db.models.deletion.CASCADE, related_name='wsm_fees', to='product.product')),
                ('variant', models.ForeignKey(blank=True, help_text='Internal. The hidden catalog row this charge rides on the order as, created automatically the first time the charge is bought.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='product.productvariant')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='OptionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your internal name for this question. Shown to shoppers only when Label is empty.', max_length=250)),
                ('label', models.CharField(blank=True, help_text='What the shopper sees above the choices, e.g. Choose a finish.', max_length=250)),
                ('prompt_type', models.CharField(choices=[('choice_one', 'Pick one'), ('choice_many', 'Pick any number'), ('text', 'Type an answer'), ('date', 'Pick a date'), ('datetime', 'Pick a date and time'), ('image', 'Upload an image')], default='choice_one', help_text='Pick one and Pick any number are answered from the choices below. The rest ask the shopper to type or upload something instead, and add no money.', max_length=20)),
                ('required', models.BooleanField(default=False, help_text='The shopper cannot add this product to the cart without answering.')),
                ('note', models.TextField(blank=True, help_text='Optional help shown to the shopper under this question.')),
                ('sort_order', models.IntegerField(default=0, help_text='Low numbers first. Ties fall back to the order created.')),
                ('product', models.ForeignKey(help_text='The product that asks this question.', on_delete=django.db.models.deletion.CASCADE, related_name='wsm_option_sets', to='product.product')),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='OptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='What the shopper sees for this choice.', max_length=250)),
                ('sku_fragment', models.CharField(blank=True, help_text='Added to the product SKU when this choice is picked, so the order and the warehouse can tell configurations apart. Has to be different from every other choice in this question. Leave blank to add nothing.', max_length=100)),
                ('price_delta', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Added to the product price when this choice is picked. A negative amount is a credit that subtracts; 0 is free. The credits on one product can never add up to more than the product's price.", max_digits=12)),
                ('image_url', models.URLField(blank=True, help_text='Optional swatch or thumbnail shown next to this choice.', max_length=500)),
                ('sort_order', models.IntegerField(default=0, help_text='Low numbers first. Ties fall back to the order created.')),
                ('option_set', models.ForeignKey(help_text='The question this is an answer to.', on_delete=django.db.models.deletion.CASCADE, related_name='values', to='wsm_compose.optionset')),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='ProductCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop65', models.BooleanField(default=False, help_text='Show the California Proposition 65 warning on this product. The storefront draws the standard short-form warning, pictogram included, unless you write your own wording below.')),
                ('prop65_text', models.TextField(blank=True, default='', help_text='Optional. Your own Prop 65 wording, e.g. the exact WARNING sentence the supplier gives you. Empty means the standard one.')),
                ('restricted_states', models.CharField(blank=True, default='', help_text='US state codes this product cannot ship to, comma separated, e.g. CA for a part that is not CARB legal. Empty restricts nothing.', max_length=255)),
                ('restriction_message', models.CharField(blank=True, default='', help_text='What the shopper reads when their destination is refused. Empty means a standard sentence naming the item and the destination.', max_length=255)),
                ('include_shipping_zones', models.ManyToManyField(blank=True, help_text='Optional. Naming zones here means this product ships ONLY to the countries those zones cover. Empty means every destination is serviced, which is what almost every product wants.', related_name='wsm_compliance_rows', to='shipping.shippingzone')),
                ('product', models.OneToOneField(help_text='The product this warning and these restrictions belong to.', on_delete=django.db.models.deletion.CASCADE, related_name='wsm_compliance', to='product.product')),
            ],
            options={
                'verbose_name': 'product compliance',
                'verbose_name_plural': 'product compliance',
            },
        ),
        migrations.CreateModel(
            name='DealerTierOptionPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_group', models.CharField(help_text='The dealer group this price is for. It has to name a group that exists, or nobody is ever charged it.', max_length=100)),
                ('price_delta', models.DecimalField(decimal_places=2, help_text='What this group pays for the choice instead of the retail amount. Never more than the retail amount; a credit is taken as written.', max_digits=12)),
                ('option_value', models.ForeignKey(help_text='The choice this group is being priced on.', on_delete=django.db.models.deletion.CASCADE, related_name='tier_deltas', to='wsm_compose.optionvalue')),
            ],
            options={
                'ordering': ('tier_group', 'pk'),
                'constraints': [models.UniqueConstraint(fields=('option_value', 'tier_group'), name='wsm_compose_one_tier_row_per_group')],
            },
        ),
    ]
