# Generated by Django 5.2.17 on 2026-09-08 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0205_merge_20260615_1308'),
        ('wsm_compose', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='product.productvariant'),
        ),
    ]
