# Generated by Django 5.2.17 on 2026-09-09 01:14

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0205_merge_20260615_1308'),
        ('wsm_compose', '0002_fee_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealertieroptionprice',
            name='option_value',
            field=models.ForeignKey(help_text='The choice this group is being priced on.', on_delete=django.db.models.deletion.CASCADE, related_name='tier_deltas', to='wsm_compose.optionvalue'),
        ),
        migrations.AlterField(
            model_name='dealertieroptionprice',
            name='price_delta',
            field=models.DecimalField(decimal_places=2, help_text='What this group pays for the choice instead of the retail amount. Never more than the retail amount; a credit is taken as written.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='dealertieroptionprice',
            name='tier_group',
            field=models.CharField(help_text='The dealer group this price is for. It has to name a group that exists, or nobody is ever charged it.', max_length=100),
        ),
        migrations.AlterField(
            model_name='fee',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='A flat charge, or the percentage when Charged as is a percentage (enter 8.25 for 8.25%). Never negative, and never above 100 for a percentage.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='fee',
            name='apply_to',
            field=models.CharField(choices=[('unit', 'Per item'), ('line', 'Once per line')], default='unit', help_text='Per item charges once for every item ordered. Once per line charges once no matter how many are ordered.', max_length=10),
        ),
        migrations.AlterField(
            model_name='fee',
            name='basis',
            field=models.CharField(choices=[('fixed', 'A flat amount of money'), ('percent', 'A percentage of the item price')], default='fixed', help_text='A flat amount of money, or a percentage of the configured product price before any other charge.', max_length=10),
        ),
        migrations.AlterField(
            model_name='fee',
            name='decline_label',
            field=models.CharField(blank=True, help_text='Only used when the charge can be declined: the wording of the decline option, e.g. No crate, I will collect.', max_length=250),
        ),
        migrations.AlterField(
            model_name='fee',
            name='label',
            field=models.CharField(help_text='What the shopper sees on the cart line, e.g. Freight crating.', max_length=250),
        ),
        migrations.AlterField(
            model_name='fee',
            name='product',
            field=models.ForeignKey(help_text='The product this charge is attached to.', on_delete=django.db.models.deletion.CASCADE, related_name='wsm_fees', to='product.product'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='required',
            field=models.BooleanField(default=True, help_text='Always charged. Turn this off to let the shopper decline the charge.'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='sku',
            field=models.CharField(blank=True, help_text='Your own code for this charge, carried through to the order.', max_length=100),
        ),
        migrations.AlterField(
            model_name='fee',
            name='variant',
            field=models.ForeignKey(blank=True, help_text='Internal. The hidden catalog row this charge rides on the order as, created automatically the first time the charge is bought.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='product.productvariant'),
        ),
        migrations.AlterField(
            model_name='optionset',
            name='label',
            field=models.CharField(blank=True, help_text='What the shopper sees above the choices, e.g. Choose a finish.', max_length=250),
        ),
        migrations.AlterField(
            model_name='optionset',
            name='name',
            field=models.CharField(help_text='Your internal name for this question. Shown to shoppers only when Label is empty.', max_length=250),
        ),
        migrations.AlterField(
            model_name='optionset',
            name='note',
            field=models.TextField(blank=True, help_text='Optional help shown to the shopper under this question.'),
        ),
        migrations.AlterField(
            model_name='optionset',
            name='product',
            field=models.ForeignKey(help_text='The product that asks this question.', on_delete=django.db.models.deletion.CASCADE, related_name='wsm_option_sets', to='product.product'),
        ),
        migrations.AlterField(
            model_name='optionset',
            name='prompt_type',
            field=models.CharField(choices=[('choice_one', 'Pick one'), ('choice_many', 'Pick any number'), ('text', 'Type an answer'), ('date', 'Pick a date'), ('datetime', 'Pick a date and time'), ('image', 'Upload an image')], default='choice_one', help_text='Pick one and Pick any number are answered from the choices below. The rest ask the shopper to type or upload something instead, and add no money.', max_length=20),
        ),
        migrations.AlterField(
            model_name='optionset',
            name='required',
            field=models.BooleanField(default=False, help_text='The shopper cannot add this product to the cart without answering.'),
        ),
        migrations.AlterField(
            model_name='optionset',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Low numbers first. Ties fall back to the order created.'),
        ),
        migrations.AlterField(
            model_name='optionvalue',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional swatch or thumbnail shown next to this choice.', max_length=500),
        ),
        migrations.AlterField(
            model_name='optionvalue',
            name='name',
            field=models.CharField(help_text='What the shopper sees for this choice.', max_length=250),
        ),
        migrations.AlterField(
            model_name='optionvalue',
            name='option_set',
            field=models.ForeignKey(help_text='The question this is an answer to.', on_delete=django.db.models.deletion.CASCADE, related_name='values', to='wsm_compose.optionset'),
        ),
        migrations.AlterField(
            model_name='optionvalue',
            name='price_delta',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Added to the product price when this choice is picked. A negative amount is a credit that subtracts; 0 is free. The credits on one product can never add up to more than the product's price.", max_digits=12),
        ),
        migrations.AlterField(
            model_name='optionvalue',
            name='sku_fragment',
            field=models.CharField(blank=True, help_text='Added to the product SKU when this choice is picked, so the order and the warehouse can tell configurations apart. Has to be different from every other choice in this question. Leave blank to add nothing.', max_length=100),
        ),
        migrations.AlterField(
            model_name='optionvalue',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Low numbers first. Ties fall back to the order created.'),
        ),
    ]
