# Generated by Django 5.2.17 on 2026-09-09 08:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0205_merge_20260615_1308'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='The exact code that names this buyer group everywhere else: on the dealer tier rows of an option value, and in the storefront. Short, lower case, no spaces, and never changed once prices point at it.', max_length=100, unique=True)),
                ('name', models.CharField(blank=True, help_text='What staff see in lists. Leave blank to show the code.', max_length=250)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='DealerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_stacking', models.BooleanField(default=False, help_text='Off (the default): a line already at a dealer price takes no voucher, promotion or order-level discount on top. On: discounts combine with dealer prices.')),
            ],
            options={
                'verbose_name_plural': 'dealer settings',
            },
        ),
        migrations.CreateModel(
            name='DealerCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_exempt', models.BooleanField(default=False, help_text='Charge this shopper no sales tax. Their exemption certificate is yours to hold on file; nothing here checks for one.')),
                ('user', models.OneToOneField(help_text="The signed-in shopper who buys at this group's prices. Search by email; the account must already exist in the store.", on_delete=django.db.models.deletion.CASCADE, related_name='wsm_dealer', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(help_text='The one buyer group whose prices this shopper gets.', on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='wsm_dealer.dealergroup')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='TierPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.PositiveIntegerField(default=1, help_text='This price applies from this quantity up, until the next break. Use 1 for the everyday price of this group.')),
                ('amount', models.DecimalField(decimal_places=3, help_text="What this group pays EACH, in the shop's currency, and at least one cent. A price, not a discount: no voucher or promotion is added on top unless discount stacking is turned on in Dealer settings.", max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('group', models.ForeignKey(help_text='The buyer group that pays this price.', on_delete=django.db.models.deletion.CASCADE, related_name='tier_prices', to='wsm_dealer.dealergroup')),
                ('variant', models.ForeignKey(help_text='The exact SKU this price is for. Search by product name or SKU.', on_delete=django.db.models.deletion.CASCADE, related_name='wsm_tier_prices', to='product.productvariant')),
            ],
            options={
                'ordering': ('variant_id', 'group_id', 'min_quantity'),
                'constraints': [models.UniqueConstraint(fields=('variant', 'group', 'min_quantity'), name='wsm_dealer_one_row_per_break'), models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('0.01'))), name='wsm_dealer_tier_amount_at_least_a_cent')],
            },
        ),
    ]
