# Generated by Django 5.2.17 on 2026-09-08 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0105_add_manage_customer_types_and_attributes_perm'),
        ('product', '0205_merge_20260615_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='DealerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_stacking', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'dealer settings',
            },
        ),
        migrations.CreateModel(
            name='DealerCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_exempt', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wsm_dealer', to='account.user')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='wsm_dealer.dealergroup')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='TierPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.PositiveIntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_prices', to='wsm_dealer.dealergroup')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wsm_tier_prices', to='product.productvariant')),
            ],
            options={
                'ordering': ('variant_id', 'group_id', 'min_quantity'),
                'constraints': [models.UniqueConstraint(fields=('variant', 'group', 'min_quantity'), name='wsm_dealer_one_row_per_break')],
            },
        ),
    ]
