# Generated by Django 5.2.17 on 2026-09-09 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0205_merge_20260615_1308'),
        ('wsm_dealer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealercustomer',
            name='group',
            field=models.ForeignKey(help_text='The one buyer group whose prices this shopper gets.', on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='wsm_dealer.dealergroup'),
        ),
        migrations.AlterField(
            model_name='dealercustomer',
            name='tax_exempt',
            field=models.BooleanField(default=False, help_text='Charge this shopper no sales tax. Their exemption certificate is yours to hold on file; nothing here checks for one.'),
        ),
        migrations.AlterField(
            model_name='dealercustomer',
            name='user',
            field=models.OneToOneField(help_text="The signed-in shopper who buys at this group's prices. Search by email; the account must already exist in the store.", on_delete=django.db.models.deletion.CASCADE, related_name='wsm_dealer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dealergroup',
            name='code',
            field=models.CharField(help_text='The exact code that names this buyer group everywhere else: on the dealer tier rows of an option value, and in the storefront. Short, lower case, no spaces, and never changed once prices point at it.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='dealergroup',
            name='name',
            field=models.CharField(blank=True, help_text='What staff see in lists. Leave blank to show the code.', max_length=250),
        ),
        migrations.AlterField(
            model_name='dealersettings',
            name='discount_stacking',
            field=models.BooleanField(default=False, help_text='Off (the default): a line already at a dealer price takes no voucher, promotion or order-level discount on top. On: discounts combine with dealer prices.'),
        ),
        migrations.AlterField(
            model_name='tierprice',
            name='amount',
            field=models.DecimalField(decimal_places=3, help_text="What this group pays EACH, in the shop's currency. A price, not a discount: no voucher or promotion is added on top unless discount stacking is turned on in Dealer settings.", max_digits=12),
        ),
        migrations.AlterField(
            model_name='tierprice',
            name='group',
            field=models.ForeignKey(help_text='The buyer group that pays this price.', on_delete=django.db.models.deletion.CASCADE, related_name='tier_prices', to='wsm_dealer.dealergroup'),
        ),
        migrations.AlterField(
            model_name='tierprice',
            name='min_quantity',
            field=models.PositiveIntegerField(default=1, help_text='This price applies from this quantity up, until the next break. Use 1 for the everyday price of this group.'),
        ),
        migrations.AlterField(
            model_name='tierprice',
            name='variant',
            field=models.ForeignKey(help_text='The exact SKU this price is for. Search by product name or SKU.', on_delete=django.db.models.deletion.CASCADE, related_name='wsm_tier_prices', to='product.productvariant'),
        ),
    ]
