# Generated by Django 5.2.17 on 2026-09-09 03:16

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0205_merge_20260615_1308'),
        ('wsm_dealer', '0002_alter_dealercustomer_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tierprice',
            name='amount',
            field=models.DecimalField(decimal_places=3, help_text="What this group pays EACH, in the shop's currency, and at least one cent. A price, not a discount: no voucher or promotion is added on top unless discount stacking is turned on in Dealer settings.", max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddConstraint(
            model_name='tierprice',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('0.01'))), name='wsm_dealer_tier_amount_at_least_a_cent'),
        ),
    ]
