# Generated by Django 5.2.17 on 2026-09-11 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0205_merge_20260615_1308"),
        ("wsm_dealer", "0003_dealersettings_catalogue_gated_dealerproductgate"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealercustomer",
            name="access_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Extra groups whose products this shopper may SEE, on top of the one above. Visibility only: they never change what this shopper pays. Leave empty unless a dealer belongs to more than one trade tier.",
                related_name="access_customers",
                to="wsm_dealer.dealergroup",
            ),
        ),
        migrations.CreateModel(
            name="DealerCategoryGate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "login_required",
                    models.BooleanField(
                        default=True,
                        help_text="On: only a signed-in dealer sees prices in this section and can buy from it. Off: this section is priced and sold to everyone, even when the whole store is gated.",
                    ),
                ),
                (
                    "category",
                    models.OneToOneField(
                        help_text="The category this rule is about, and everything under it.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wsm_gate",
                        to="product.category",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Leave empty to let any dealer group see this section. Name groups to let only those groups see it. Visibility only: what each group PAYS is its tier prices.",
                        related_name="gated_categories",
                        to="wsm_dealer.dealergroup",
                    ),
                ),
            ],
            options={
                "ordering": ("category_id",),
            },
        ),
    ]
