import pytest
from django.contrib.auth.hashers import check_password, identify_hasher

from saleor import settings as production_settings

from ..hashers import (
    SHA512Base64PBKDF2PasswordHasher,
    WSMMD5PasswordHasher,
    WSMSHA256PasswordHasher,
    php_strtolower,
)


def test_encode_and_verify_sha512_base64_pbkdf2():
    generated_token = SHA512Base64PBKDF2PasswordHasher().encode(
        "Saleor123!", salt=SHA512Base64PBKDF2PasswordHasher().salt()
    )
    assert 90 == len(generated_token)
    assert SHA512Base64PBKDF2PasswordHasher().verify("Saleor123!", generated_token)


# Vectors below were generated by the real legacy platform: PHP 7.4.33 running
# core's own expressions (`hash('sha256', strtolower($pw)."-wsm-".$salt)` and
# `md5()`) inside the webshopmanager/core image. Do not "fix" them by hand -- if
# one fails, the hasher diverged from what core wrote to `customer.password`.
CAFE = "Café123Ä"  # non-ASCII upper-case: PHP folds only A-Z, Python folds Ä too

WSM_SHA256_VECTORS = [
    ("secret123", "e3b0c44298fc1c149afbf4c8996fb92427ae41e4",
     "d6ea96a288fb7771a1cd726647bde6ec29a4f62d8ab931761cf96ac4c5adb648"),
    ("SecretPass1", "0beec7b5ea3f0fdbc95d0dd47f3c5bc275da8a33",
     "69c7cba3b78d05f52ee4992ff50774e03cd296b8df6c373e17fe8f1172944380"),
    (CAFE, "b6589fc6ab0dc82cf12099d1c2d40ab994e8410c",
     "a316d5df4580af81eb42d1df4d0ee79d8771ac197a88fd3211aba1bd2788887b"),
    ("p@ss$word!", "356a192b7913b04c54574d18c28d46e6395428ab",
     "9249076b0160a1e12b1d46cbe9c1235748499334f594e66cdf78136d0d797820"),
]

WSM_MD5_RAW_VECTORS = [
    ("secret123", "5d7845ac6ee7cfffafc5fe5f35cf666d"),
    ("SecretPass1", "b0d787acc99926f19eed0d686d8a5c9a"),
    (CAFE, "eaa75998a74705a15eef553fa04909eb"),
    ("p@ss$word!", "6f2acb85061e0081de10e6ba445fe548"),
]

WSM_MD5_LOWERED_VECTORS = [
    ("SecretPass1", "907a1712b3b1f60f560797bfdf4f57a1"),
    (CAFE, "78b74579d7efefadf6ca1a0df6a8b1ba"),
]


@pytest.mark.parametrize(("password", "salt", "digest"), WSM_SHA256_VECTORS)
def test_wsm_sha256_verifies_hash_written_by_core(password, salt, digest):
    hasher = WSMSHA256PasswordHasher()
    encoded = f"wsm_sha256${salt}${digest}"

    assert hasher.encode(password, salt) == encoded
    assert hasher.verify(password, encoded)


@pytest.mark.parametrize(("password", "salt", "digest"), WSM_SHA256_VECTORS)
def test_wsm_sha256_rejects_wrong_password(password, salt, digest):
    encoded = f"wsm_sha256${salt}${digest}"

    assert not WSMSHA256PasswordHasher().verify(password + "x", encoded)


def test_wsm_sha256_is_case_insensitive_like_core():
    # core lower-cased before hashing, so every casing of the password matched.
    hasher = WSMSHA256PasswordHasher()
    salt = "0beec7b5ea3f0fdbc95d0dd47f3c5bc275da8a33"
    encoded = f"wsm_sha256${salt}$69c7cba3b78d05f52ee4992ff50774e03cd296b8df6c373e17fe8f1172944380"

    assert hasher.verify("SecretPass1", encoded)
    assert hasher.verify("secretpass1", encoded)
    assert hasher.verify("SECRETPASS1", encoded)


def test_wsm_sha256_folds_only_ascii():
    # Python's str.lower() would fold "Ä" and produce a different digest than the
    # one core stored; php_strtolower must leave it alone.
    assert php_strtolower(CAFE) == "café123Ä".encode()
    assert php_strtolower(CAFE) != CAFE.lower().encode()


@pytest.mark.parametrize(("password", "digest"), WSM_MD5_RAW_VECTORS)
def test_wsm_md5_verifies_password_as_typed(password, digest):
    encoded = f"wsm_md5$${digest}"

    assert WSMMD5PasswordHasher().encode(password) == encoded
    assert WSMMD5PasswordHasher().verify(password, encoded)


@pytest.mark.parametrize(("password", "digest"), WSM_MD5_LOWERED_VECTORS)
def test_wsm_md5_verifies_lower_cased_variant(password, digest):
    # core's pre-salt branch accepted md5(strtolower($pw)) as well.
    encoded = f"wsm_md5$${digest}"

    assert WSMMD5PasswordHasher().verify(password, encoded)


def test_wsm_md5_rejects_wrong_password():
    encoded = "wsm_md5$$5d7845ac6ee7cfffafc5fe5f35cf666d"

    assert not WSMMD5PasswordHasher().verify("secret124", encoded)


SHA256_ENCODED = (
    "wsm_sha256$e3b0c44298fc1c149afbf4c8996fb92427ae41e4$"
    "d6ea96a288fb7771a1cd726647bde6ec29a4f62d8ab931761cf96ac4c5adb648"
)
MD5_ENCODED = "wsm_md5$$5d7845ac6ee7cfffafc5fe5f35cf666d"


@pytest.fixture
def production_password_hashers(settings):
    """Restore the real hasher list.

    `saleor.tests.settings` swaps every hasher for a dummy to keep the suite
    fast, which would hide whether these hashers are actually reachable.
    """
    settings.PASSWORD_HASHERS = production_settings.PASSWORD_HASHERS
    return settings.PASSWORD_HASHERS


def test_wsm_hashers_are_registered_in_production_settings():
    hashers = production_settings.PASSWORD_HASHERS

    assert "saleor.core.hashers.WSMSHA256PasswordHasher" in hashers
    assert "saleor.core.hashers.WSMMD5PasswordHasher" in hashers
    # They must never be preferred: entry 0 is what new passwords are hashed with.
    assert hashers[0] == "django.contrib.auth.hashers.PBKDF2PasswordHasher"


@pytest.mark.parametrize("encoded", [SHA256_ENCODED, MD5_ENCODED])
def test_wsm_hashers_are_installed_and_identifiable(
    encoded, production_password_hashers
):
    # A hash Django cannot identify makes check_password() return False silently,
    # so assert the settings wiring, not just the classes.
    assert identify_hasher(encoded).algorithm == encoded.split("$", 1)[0]


@pytest.mark.parametrize(
    ("hasher", "encoded"),
    [
        (WSMSHA256PasswordHasher(), SHA256_ENCODED),
        (WSMMD5PasswordHasher(), MD5_ENCODED),
    ],
)
def test_wsm_hashers_always_ask_to_be_upgraded(
    hasher, encoded, production_password_hashers
):
    assert hasher.must_update(encoded) is True
    assert check_password("secret123", encoded)


@pytest.mark.parametrize("encoded", [SHA256_ENCODED, MD5_ENCODED])
def test_legacy_login_rehashes_to_the_preferred_hasher(
    encoded, customer_user, production_password_hashers
):
    """The point of the whole exercise: one legacy login, then modern hashing.

    `tokenCreate` authenticates through `User.check_password()`, which passes a
    setter to Django, so a correct legacy password is re-hashed and saved.
    """
    customer_user.password = encoded
    customer_user.save(update_fields=["password"])

    assert customer_user.check_password("secret123")

    customer_user.refresh_from_db()
    assert customer_user.password.startswith("pbkdf2_sha256$")
    assert customer_user.check_password("secret123")
    assert not customer_user.check_password("wrong-password")


def test_wrong_legacy_password_does_not_rehash(
    customer_user, production_password_hashers
):
    customer_user.password = SHA256_ENCODED
    customer_user.save(update_fields=["password"])

    assert not customer_user.check_password("not-the-password")

    customer_user.refresh_from_db()
    assert customer_user.password == SHA256_ENCODED


def test_wsm_hashers_refuse_to_hash_new_passwords():
    # Guardrail: nothing should ever *write* a legacy hash.
    with pytest.raises(NotImplementedError):
        WSMSHA256PasswordHasher().salt()
    with pytest.raises(NotImplementedError):
        WSMMD5PasswordHasher().salt()


def test_wsm_hashers_safe_summary_masks_the_digest():
    encoded = "wsm_md5$$5d7845ac6ee7cfffafc5fe5f35cf666d"

    summary = WSMMD5PasswordHasher().safe_summary(encoded)

    assert "5d7845ac6ee7cfffafc5fe5f35cf666d" not in str(summary.values())
