# Generated by Django 5.2.17 on 2026-09-09 08:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0205_merge_20260615_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_kind', models.CharField(choices=[('fixed', 'An amount off the whole kit'), ('percent', 'A percentage off the whole kit')], default='fixed', help_text="Whether the saving below is money off the kit or a share of what the kit's own members add up to.", max_length=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text="The saving off the members' own prices added up: an amount in the shop's currency, or a percentage, per the kind above. 0 sells the kit at the sum of its parts.", max_digits=12)),
                ('freight_class', models.CharField(blank=True, help_text='Freight class for the kit as one shipment. Blank leaves shipping to work off the members.', max_length=50)),
                ('active', models.BooleanField(default=True, help_text='Off takes the kit price away; the members still sell on their own.')),
                ('collection', models.OneToOneField(help_text="The collection this kit is sold as. Its products are the kit's members, listed below with the quantity of each.", on_delete=django.db.models.deletion.CASCADE, related_name='wsm_kit', to='product.collection')),
            ],
            options={
                'verbose_name': 'kit',
                'verbose_name_plural': 'kits',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='SeriesConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='The one brand this series covers. A series is never mixed-brand.', max_length=250)),
                ('axes', models.JSONField(blank=True, default=list, help_text='The questions the configurator asks, in order, as product attribute slugs.')),
                ('partitioning_axis', models.CharField(help_text='The one axis that decides WHICH product the shopper ends up on. It must be one of the axes above, and every member of the collection must carry that attribute, or publishing is refused.', max_length=250)),
                ('miss_message', models.TextField(blank=True, help_text="What a shopper is told when their answers match nothing in this series. Leave blank for the storefront's standard wording.")),
                ('published', models.BooleanField(default=False, help_text='Show this series on the storefront. Saving with this on is refused unless the collection has 2 or more published products and every one of them carries the partitioning attribute.')),
                ('collection', models.OneToOneField(help_text='The collection whose products this series configures. Which products are in it is managed on the collection itself, in the Saleor dashboard.', on_delete=django.db.models.deletion.CASCADE, related_name='wsm_series', to='product.collection')),
            ],
            options={
                'verbose_name': 'series',
                'verbose_name_plural': 'series',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='KitMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='How many of this SKU one kit contains, and at least one.', validators=[django.core.validators.MinValueValidator(1)])),
                ('sort_order', models.IntegerField(default=0, help_text='Lowest first. Members with the same number fall back to the order added.')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='wsm_containers.kitconfig')),
                ('variant', models.ForeignKey(help_text='The SKU this kit contains. Search by product name or SKU.', on_delete=django.db.models.deletion.CASCADE, related_name='wsm_kit_memberships', to='product.productvariant')),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
                'constraints': [models.UniqueConstraint(fields=('kit', 'variant'), name='wsm_containers_one_row_per_kit_variant')],
            },
        ),
    ]
