# Generated by Django 5.2.17 on 2026-09-08 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("product", "0205_merge_20260615_1308"),
    ]

    operations = [
        migrations.CreateModel(
            name="KitConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount_kind",
                    models.CharField(
                        choices=[("fixed", "fixed"), ("percent", "percent")],
                        default="fixed",
                        max_length=10,
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Currency, or percent.",
                        max_digits=12,
                    ),
                ),
                ("freight_class", models.CharField(blank=True, max_length=50)),
                ("active", models.BooleanField(default=True)),
                (
                    "collection",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wsm_kit",
                        to="product.collection",
                    ),
                ),
            ],
            options={
                "ordering": ("pk",),
            },
        ),
        migrations.CreateModel(
            name="SeriesConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=250)),
                ("axes", models.JSONField(blank=True, default=list)),
                ("partitioning_axis", models.CharField(max_length=250)),
                ("miss_message", models.TextField(blank=True)),
                ("published", models.BooleanField(default=False)),
                (
                    "collection",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wsm_series",
                        to="product.collection",
                    ),
                ),
            ],
            options={
                "ordering": ("pk",),
            },
        ),
        migrations.CreateModel(
            name="KitMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "kit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="wsm_containers.kitconfig",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wsm_kit_memberships",
                        to="product.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "pk"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kit", "variant"),
                        name="wsm_containers_one_row_per_kit_variant",
                    )
                ],
            },
        ),
    ]
