# Generated by Django 5.2.17 on 2026-09-10 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsm_containers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitMemberRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('requires_one_of', 'Needs at least one of'), ('excludes', 'Cannot be sold with')], default='requires_one_of', help_text='Whether the part above needs one of the parts you pick below, or cannot be sold together with them.', max_length=20)),
                ('message', models.TextField(help_text='What the shopper is told when this rule stops the kit going into the cart, in your own words, e.g. Requires Manual or HD Tensioner.')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='wsm_containers.kitconfig')),
                ('subject', models.ForeignKey(help_text='The part this rule is about.', on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='wsm_containers.kitmember')),
                ('targets', models.ManyToManyField(help_text='The other parts in this kit the rule is about.', related_name='rules_targeting', to='wsm_containers.kitmember')),
            ],
            options={
                'verbose_name': 'kit rule',
                'verbose_name_plural': 'kit rules',
                'ordering': ('pk',),
            },
        ),
    ]
