# Generated by Django 5.2.17 on 2026-09-09 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0205_merge_20260615_1308'),
        ('wsm_containers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitconfig',
            name='active',
            field=models.BooleanField(default=True, help_text='Off takes the kit price away; the members still sell on their own.'),
        ),
        migrations.AlterField(
            model_name='kitconfig',
            name='collection',
            field=models.OneToOneField(help_text="The collection this kit is sold as. Its products are the kit's members, listed below with the quantity of each.", on_delete=django.db.models.deletion.CASCADE, related_name='wsm_kit', to='product.collection'),
        ),
        migrations.AlterField(
            model_name='kitconfig',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text="The saving off the members' own prices added up: an amount in the shop's currency, or a percentage, per the kind above. 0 sells the kit at the sum of its parts.", max_digits=12),
        ),
        migrations.AlterField(
            model_name='kitconfig',
            name='discount_kind',
            field=models.CharField(choices=[('fixed', 'fixed'), ('percent', 'percent')], default='fixed', help_text="How the saving below is read: 'fixed' is an amount off the whole kit, 'percentage' is a share off it.", max_length=10),
        ),
        migrations.AlterField(
            model_name='kitconfig',
            name='freight_class',
            field=models.CharField(blank=True, help_text='Freight class for the kit as one shipment. Blank leaves shipping to work off the members.', max_length=50),
        ),
        migrations.AlterField(
            model_name='kitmember',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='How many of this SKU one kit contains.'),
        ),
        migrations.AlterField(
            model_name='kitmember',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Lowest first. Members with the same number fall back to the order added.'),
        ),
        migrations.AlterField(
            model_name='kitmember',
            name='variant',
            field=models.ForeignKey(help_text='The SKU this kit contains. Search by product name or SKU.', on_delete=django.db.models.deletion.CASCADE, related_name='wsm_kit_memberships', to='product.productvariant'),
        ),
        migrations.AlterField(
            model_name='seriesconfig',
            name='axes',
            field=models.JSONField(blank=True, default=list, help_text='The questions the configurator asks, in order, as product attribute slugs.'),
        ),
        migrations.AlterField(
            model_name='seriesconfig',
            name='brand',
            field=models.CharField(help_text='The one brand this series covers. A series is never mixed-brand.', max_length=250),
        ),
        migrations.AlterField(
            model_name='seriesconfig',
            name='collection',
            field=models.OneToOneField(help_text='The collection whose products this series configures. Which products are in it is managed on the collection itself, in the Saleor dashboard.', on_delete=django.db.models.deletion.CASCADE, related_name='wsm_series', to='product.collection'),
        ),
        migrations.AlterField(
            model_name='seriesconfig',
            name='miss_message',
            field=models.TextField(blank=True, help_text="What a shopper is told when their answers match nothing in this series. Leave blank for the storefront's standard wording."),
        ),
        migrations.AlterField(
            model_name='seriesconfig',
            name='partitioning_axis',
            field=models.CharField(help_text='The one axis that decides WHICH product the shopper ends up on. It must be one of the axes above, and every member of the collection must carry that attribute, or publishing is refused.', max_length=250),
        ),
        migrations.AlterField(
            model_name='seriesconfig',
            name='published',
            field=models.BooleanField(default=False, help_text='Show this series on the storefront. Saving with this on is refused unless the collection has 2 or more published products and every one of them carries the partitioning attribute.'),
        ),
    ]
