# Generated by Django 5.2.17 on 2026-09-11 07:53
"""Slots: ONE additive migration, zero renames, and the backfill that keeps prices.

Additive because the names are the contract. `KitConfig`, `KitMember`,
`KitMemberRule` and every `Wsm*` GraphQL type built on them are what the
Dashboard, the storefront and the stage console rows address today, so this
migration adds a table, one nullable FK and three nullable columns, and renames
nothing.

THE BACKFILL IS WHY A KIT STILL COSTS WHAT IT COST. Every existing kit gets ONE
slot holding all of its members, and that slot has no `partitioning_axis`, which
is the data that says "take every candidate that survives" rather than "ask the
shopper to pick one". So `pricing_members` sees the same rows in the same order
and the acceptance kit is still 9358.19 at retail. Kits with no members are
skipped: a slot for a role nothing can fill is a row nobody would ever read.

An existing `SeriesConfig` is NOT backfilled into a `KitConfig`. It reads as a
one-slot container through `containers/resolve.py`, which costs no rows at all;
materialising one kit row per series would be a fleet-wide write across 3,362
Desert Rat series that no merchant asked for, and it would put every one of them
into the Dashboard's kit list overnight.
"""

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

# What the one backfilled slot is called on a kit whose merchant never named a
# role. Read on a storefront, so it is a sentence a shopper could see and not a
# placeholder.
BACKFILL_SLOT_LABEL = "Included parts"


def put_every_member_in_one_fixed_slot(apps, schema_editor):
    """One slot per kit that has members, holding all of them. No price moves.

    Iterated rather than bulk-created because the slot's pk is what the members
    are then pointed at, and a kit estate is hundreds of rows, not millions.
    """
    KitConfig = apps.get_model("wsm_containers", "KitConfig")
    KitMember = apps.get_model("wsm_containers", "KitMember")
    ContainerSlot = apps.get_model("wsm_containers", "ContainerSlot")
    database = schema_editor.connection.alias

    kits = (
        KitConfig.objects.using(database)
        .filter(members__isnull=False)
        .distinct()
        .order_by("pk")
    )
    for kit in kits:
        slot = ContainerSlot.objects.using(database).create(
            kit=kit,
            label=BACKFILL_SLOT_LABEL,
            quantity=1,
            required=True,
            sort_order=0,
            axes=[],
            partitioning_axis="",
            miss_message="",
        )
        KitMember.objects.using(database).filter(kit=kit, slot__isnull=True).update(
            slot=slot
        )


def take_every_member_out_of_its_slot(apps, schema_editor):
    """The members are unpointed FIRST, because the FK cascades.

    Deleting the slots while a member still points at one deletes the member,
    which would turn a reverse migration into data loss on the kits this
    migration was supposed to leave alone.
    """
    database = schema_editor.connection.alias
    apps.get_model("wsm_containers", "KitMember").objects.using(database).update(
        slot=None
    )
    apps.get_model("wsm_containers", "ContainerSlot").objects.using(
        database
    ).all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0205_merge_20260615_1308"),
        ("wsm_containers", "0002_kitmemberrule"),
    ]

    operations = [
        migrations.AddField(
            model_name="kitconfig",
            name="brand",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The one brand this container covers, when it covers exactly one. Blank for a mixed-brand bundle.",
                max_length=250,
            ),
        ),
        migrations.AddField(
            model_name="kitconfig",
            name="miss_message",
            field=models.TextField(
                blank=True,
                default="",
                help_text="What a shopper is told when their vehicle leaves a required part of this container with nothing that fits. A slot's own sentence wins over this one. Blank for the storefront's standard wording.",
            ),
        ),
        migrations.AddField(
            model_name="kitconfig",
            name="published",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Show this container as its own shoppable page. Unset means the container has never been published or hidden by hand, and `active` answers for it.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ContainerSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="What this part of the container is called, in the merchant's own words: Exhaust, Tuner, Gauge.",
                        max_length=250,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="How many of whatever fills this slot one container contains.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "required",
                    models.BooleanField(
                        default=True,
                        help_text="A required slot with nothing that fits the shopper's vehicle refuses the whole container, in the sentence below.",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0,
                        help_text="Lowest first. Slots with the same number fall back to the order added.",
                    ),
                ),
                (
                    "axes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="The questions this slot asks AFTER the vehicle has answered fitment, in order, as product attribute slugs.",
                    ),
                ),
                (
                    "partitioning_axis",
                    models.CharField(
                        blank=True,
                        help_text="The one axis that decides WHICH of the fitting candidates the shopper ends up on. Blank means this slot takes every candidate that fits rather than asking the shopper to choose.",
                        max_length=250,
                    ),
                ),
                (
                    "miss_message",
                    models.TextField(
                        blank=True,
                        help_text="What a shopper is told when nothing in this slot fits their vehicle. Blank falls back to the container's own sentence.",
                    ),
                ),
                (
                    "kit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="wsm_containers.kitconfig",
                    ),
                ),
                (
                    "source_collection",
                    models.ForeignKey(
                        blank=True,
                        help_text="Fill this slot from another container's collection instead of listing candidates by hand, so a kit can hold a series and the series stays the one place its members are edited.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wsm_container_slots",
                        to="product.collection",
                    ),
                ),
            ],
            options={
                "verbose_name": "container slot",
                "verbose_name_plural": "container slots",
                "ordering": ("sort_order", "pk"),
            },
        ),
        migrations.AddField(
            model_name="kitmember",
            name="slot",
            field=models.ForeignKey(
                blank=True,
                help_text="The role this part fills in the container. A slot's candidates go with the slot when it is deleted, because a candidate for a role that no longer exists is not a part of anything.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidates",
                to="wsm_containers.containerslot",
            ),
        ),
        migrations.AddConstraint(
            model_name="containerslot",
            constraint=models.UniqueConstraint(
                fields=("kit", "label"), name="wsm_containers_one_slot_per_label"
            ),
        ),
        # WSM-CORE-SAFE: reads and writes wsm_containers_kitconfig, wsm_containers_containerslot and wsm_containers_kitmember, and no other table.
        migrations.RunPython(
            put_every_member_in_one_fixed_slot,
            take_every_member_out_of_its_slot,
        ),
    ]
