# Generated by Django 5.2.17 on 2026-09-09 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsm_containers', '0002_alter_kitconfig_active_alter_kitconfig_collection_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kitconfig',
            options={'ordering': ('pk',), 'verbose_name': 'kit', 'verbose_name_plural': 'kits'},
        ),
        migrations.AlterModelOptions(
            name='seriesconfig',
            options={'ordering': ('pk',), 'verbose_name': 'series', 'verbose_name_plural': 'series'},
        ),
        migrations.AlterField(
            model_name='kitconfig',
            name='discount_kind',
            field=models.CharField(choices=[('fixed', 'An amount off the whole kit'), ('percent', 'A percentage off the whole kit')], default='fixed', help_text="Whether the saving below is money off the kit or a share of what the kit's own members add up to.", max_length=10),
        ),
    ]
