# Generated by Django 5.2.17 on 2026-09-09 03:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsm_containers', '0002_alter_kitconfig_active_alter_kitconfig_collection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitmember',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='How many of this SKU one kit contains, and at least one.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
